### ISSUE TITLE
Feature request: Get tracks from post

### ISSUE THREAD

**Issue by abvadabra** [bogem/vnehm#1]
It would be nice to have ability to download tracks not only from personal playlist but also from the direct link to the post which contains them.
It can be implemented via command like `vnehm get <url>`

Example usage:
`vnehm get https://vk.com/wall1456047_28007` will download and add tracks by Kvelertak from this post into my iTunes playlist

**Comment by n10v** [comment]
Hm, it's a good idea 
I will implement it during next week

**Comment by abvadabra** [comment]
Great! Thank you!

**Comment by n10v** [comment]
So I implemented this feature. Please update vnehm and test it. If you have some advices or offers, don't hesitate to tell.
