### ISSUE TITLE
Error during tag parsing terminates processing of track

### ISSUE THREAD

**Issue by abvadabra** [bogem/vnehm#2]
I am not sure that it's reasonable to stop track processing if it's tag couldn't be parsed. After all, it's not a critical issue, maybe a warning can be enough.

If I am wrong and tag is necessary please tell me.

I am referring to these lines https://github.com/bogem/vnehm/blob/master/tracksprocessor/tracks_processor.go#L71

Writing this because just ran into an issue that I am not able to get track as it has old version of ID3v2 tag :)

**Comment by n10v** [comment]
You're write isn't really necessary and it shouldn't be the reason, why downloading stops at all. 
I should consider, how to better fix it
Most probably I will fix it today

**Comment by n10v** [comment]
And thank you for reporting this bug!

**Comment by abvadabra** [comment]
I must correct that it doesn't stops the downloading, the file has been downloaded without issues. It just prevents track from being added into iTunes

**Comment by n10v** [comment]
Yes sorry, I mistook. I'm sleepy now😅

**Comment by bogem** [comment]
Please write the name of track, that you tried to download
